catalog/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("books/", views.BookListView.as_view(), name="books"),
    path(
        "bookinst-manage/",
        views.LoanedBooksManageListView.as_view(),
        name="bookinst-manage",
    ),
    path(
        "book/<uuid:pk>/renew/", views.renew_book_librarian, name="renew-book-librarian"
    ),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("mybooks/", views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
    path("author/create/", views.AuthorCreate.as_view(), name="author-create"),
    path("author/<int:pk>/update/", views.AuthorUpdate.as_view(), name="author-update"),
    path("author/<int:pk>/delete/", views.AuthorDelete.as_view(), name="author-delete"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from locallibrary import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("", RedirectView.as_view(url="catalog/")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# accounts/ login/ [name='login']
# accounts/ logout/ [name='logout']
# accounts/ password_change/ [name='password_change']
# accounts/ password_change/done/ [name='password_change_done']
# accounts/ password_reset/ [name='password_reset']
# accounts/ password_reset/done/ [name='password_reset_done']
# accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/ reset/done/ [name='password_reset_complete']

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid
from datetime import date


class Genre(models.Model):
    """Model representing a book genre."""

    name = models.CharField(
        max_length=200, help_text="Enter a book genre (e.g.Science Fiction)"
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""

    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book"
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text='13 Character <ahref="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
    )
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular bookacross whole library",
    )
    book = models.ForeignKey("Book", on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ("m", "Maintenance"),
        ("o", "On loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Book availability",
    )

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    class Meta:
        ordering = ["due_back"]
        permissions = (
            ("view_list_on_loan", "Get all book on loan"),
            ("can_mark_returned", "Can mark returned book"),
        )

        def __str__(self):
            """String for representing the Model object."""
            return f"{self.id} ({self.book.title})"


class Author(models.Model):
    """Model representing an author."""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.last_name}, {self.first_name}"

catalog/forms.py
import datetime
from django import forms
from django.forms import ModelForm
from bootstrap_datepicker_plus.widgets import DatePickerInput
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from catalog.models import BookInstance


class RenewBookModelForm(ModelForm):
    def clean_renewal_date(self):
        data = self.cleaned_data["renewal_date"]

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("Invalid date - renewal more than 4 weeks ahead"))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        fields = ["due_back"]
        labels = {"due_back": _("Renewal date")}
        help_texts = {
            "due_back": _("Enter a date between now and 4 weeks (default 3).")
        }
        widgets = {"due_back": DatePickerInput()}

catalog/views.py
from django.utils.translation import gettext
from django.http import Http404
from catalog.models import Book, Author, BookInstance
from django.views import generic
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookModelForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.


def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact="a").count()
    num_authors = Author.objects.count()
    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits + 1
    age_cookie = request.session.get_session_cookie_age()
    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_visits": num_visits,
        "age_cookie": datetime.timedelta(seconds=age_cookie),
    }

    return render(request, "index.html", context=context)


class BookListView(generic.ListView):
    model = Book
    # your own name for the list as a template variable
    paginate_by = 2

    def get_queryset(self):
        return Book.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        return context


class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        try:
            book = Book.objects.get(pk=primary_key)
        except Book.DoesNotExist:
            raise Http404(gettext("Book does not exist"))

        return render(request, "catalog/book_detail.html", context={"book": book})

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context["book_instance"] = context["book"].bookinstance_set.order_by(
            "-due_back"
        )
        return context


class AuthorListView(generic.ListView):
    model = Author
    # your own name for the list as a template variable
    paginate_by = 2

    def get_queryset(self):
        return Author.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(AuthorListView, self).get_context_data(**kwargs)
        # # Create any data and add it to the context
        # context["some_data"] = "This is just some data"
        return context


class AuthorDetailView(generic.DetailView):
    model = Author

    def author_detail_view(request, primary_key):
        try:
            author = Author.objects.get(pk=primary_key).select_related("book")
        except Author.DoesNotExist:
            raise Http404(gettext("Author does not exist"))

        return render(request, "author/author_detail.html", context={"author": author})

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context["books"] = context["author"].book_set.all()
        return context


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""

    model = BookInstance
    template_name = "catalog/bookinstance_list_borrowed_user.html"
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact="o")
            .order_by("due_back")
        )


class LoanedBooksManageListView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.ListView
):
    """Generic class-based view listing books on loan to current user."""

    model = BookInstance
    permission_required = "catalog.view_list_on_loan"
    template_name = "catalog/bookinstance_manage.html"
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.all()
            .filter(status__exact="o")
            .order_by("-due_back")
            .select_related("borrower")
        )


@login_required
@permission_required("catalog.can_mark_returned", raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == "POST":
        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookModelForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data["due_back"]
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse("bookinst-manage"))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm(initial={"due_back": proposed_renewal_date})

    context = {
        "form": form,
        "book_instance": book_instance,
    }

    return render(request, "catalog/book_renew_librarian.html", context)


class AuthorCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Author
    permission_required = "catalog.create_author"
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    initial = {"date_of_death": "11/06/2020"}


class AuthorUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Author
    permission_required = "catalog.change_author"

    fields = (
        "__all__"  # Not recommended (potential security issue if more fields added)
    )


class AuthorDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Author
    permission_required = "catalog.delete_author"
    success_url = reverse_lazy("authors")

catalog/templates/base_generic.html
{% load bootstrap5 %}
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Local Library</title>
    {% endblock title %}
    <meta charset="utf-8"
          name="viewport"
          content="width=device-width, initial-scale=1" />
    <meta name="description" />
    <meta name="keywords" />
    {% bootstrap_css %}
    <!-- Add additional CSS in static file  -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          {% block nav %}
            {% include "navbar.html" %}
          {% endblock nav %}
        </div>
      </div>
      <div class="row pl-20">
        <div class="col-sm-10">
          <div class="row ">
            {% block content %}
            {% endblock content %}
          </div>
          <div class="row">{% include "pagination.html" %}</div>
        </div>
      </div>
    </div>
  </body>
</html>

catalog/templates/index.html
{% extends "base_generic.html" %}
{% block title %}
  {% load i18n %}
  <title>{% trans "Home Library" %}</title>
{% endblock title %}
{% block content %}
  <h1>{% trans "Home Library" %}</h1>
  <p>
    {% trans "Welcome to LocalLibrary, a website developed by" %}
    <em>{% trans "Mozilla Developer Network" %}</em>!
  </p>
  <h2>{% trans "Dynamic content" %}</h2>
  <p>{% trans "The library has the following record counts:" %}</p>
  <ul>
    <li>
      <strong>{% trans "Books:" %}</strong>
      {{ num_books }}
    </li>
    <li>
      <strong>{% trans "Copies:" %}</strong> {{ num_instances }}
    </li>
    <li>
      <strong>{% trans "Copies available:" %}</strong>
      {{ num_instances_available }}
    </li>
    <li>
      <strong>{% trans "Authors:" %}</strong> {{ num_authors }}
    </li>
  </ul>
  <p>
    You have visited this page {{ num_visits }} time
    {% if num_visits > 1 %}s{% endif %}
    .
  </p>
  <p>{{ age_cookie }}</p>
{% endblock content %}

catalog/templates/navbar.html
{% load static %}
{% load i18n %}
<script type="text/javascript" src="{% static 'js/action_navbar.js' %}"></script>
<section class="navigation">
  <div class="nav-container">
    <div class="brand">
      <a href="{% url 'index' %}">Logo</a>
    </div>
    <nav>
      <ul class="nav-list">
        <li>
          <a href="{% url 'index' %}">{% trans "Home" %}</a>
        </li>
        <li>
          <a href="{% url 'books' %}">{% trans "Book" %}</a>
        </li>
        <li>
          <a href="{% url 'authors' %}">{% trans "Author" %}</a>
        </li>
        <li>
          <a href="#!">{% trans "Manage" %}</a>
          <ul class="navbar-dropdown">
            {% if perms.catalog.view_list_on_loan %}
              <li>
                <a href="{% url 'bookinst-manage' %}">{% trans "Manage Book Instance" %}</a>
              </li>
            {% endif %}
            {% if perms.catalog.add_author %}
              <li>
                <a href="{% url 'author-create' %}">{% trans "Create Author" %}</a>
              </li>
            {% endif %}
            <li>
              <a href="{% url 'index' %}">Stylus</a>
            </li>
          </ul>
        </li>
        {% if user.is_authenticated %}
          <li>
            <a href="#">{% trans "Name" %}: {{ user.get_username }}</a>
            <ul class="navbar-dropdown">
              <li>
                <a href="{% url 'my-borrowed' %}">{% trans "My Borrowed" %}</a>
              </li>
              <li>
                <a href="{% url 'logout' %}?next={{ request.path }}">{% trans "Logout" %}</a>
              </li>
            </ul>
          </li>
        {% else %}
          <li>
            <a href="{% url 'login' %}?next={{ request.path }}">{% trans "Login" %}</a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <div class="box-select">{% include "select_language.html" %}</div>
  </div>
</section>
<script>
  document
    .getElementById("language-select")
    .addEventListener("change", function () {
      document.getElementById("language-form").submit();
    });
</script>

catalog/templates/pagination.html
{% load i18n %}
<div class="row">
  {% block pagination %}
    {% if is_paginated %}
      <div class="pagination">
        <span class="page-links">
          {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
          <span class="page-current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
          {% if page_obj.has_next %}<a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>{% endif %}
        </span>
      </div>
    {% endif %}
  {% endblock pagination %}
</div>

catalog/templates/select_language.html
{% load i18n %}
{% load static %}
<div class="box-select">
  <form id="language-form" action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
    <input name="next" type="hidden" value="{{ request.path }}" />
    <label for="language-select" hidden>The label</label>
    <select id="language-select" name="language">
      {% get_current_language as LANGUAGE_CODE %}
      {% get_available_languages as LANGUAGES %}
      {% for lang in LANGUAGES %}
        <option value="{{ lang.0 }}"
                {% if lang.0 == LANGUAGE_CODE %}selected{% endif %}>{{ lang.1 }}</option>
      {% endfor %}
    </select>
  </form>
</div>